version: "3.7"

services:
  # # Postgres
  # fido_service.db:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - fido_service_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB_NAME:?err}
  #     POSTGRES_USER: ${POSTGRES_USER:?err}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
  #   container_name: fido_service-db

  # Application
  fido_service.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fido_service.api:latest
    command: ./scripts/run-server.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # depends_on:
    #   - fido_service.db
    container_name: fido_service-api

volumes:
  fido_service_data:
